language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0

before_script:
    - cp ./tests/php-unix.sample.ini ./tests/php.ini
    - if [ "$TRAVIS_PHP_VERSION" == "hhvm" -o "$TRAVIS_PHP_VERSION" == "hhvm-nightly" ]; then cp ./tests/dbals.hhvm.ini ./tests/dbals.ini; fi
    - if ! [ "$TRAVIS_PHP_VERSION" == "hhvm" -o "$TRAVIS_PHP_VERSION" == "hhvm-nightly" ]; then cp ./tests/dbals.sample.ini ./tests/dbals.ini; fi
    - cp ./tests/drivers.sample.ini ./tests/drivers.ini

    - psql -c 'CREATE DATABASE nextras_migrations_test' -U postgres
    - mysql -e 'CREATE DATABASE nextras_migrations_test;'
    - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql

    - composer install --no-interaction

script:
    - ./tests/run.sh ./tests/cases
