language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0

before_script:
    - cp ./tests/php-unix.sample.ini ./tests/php.ini
    - cp ./tests/dbals.sample.ini ./tests/dbals.ini
    - cp ./tests/drivers.sample.ini ./tests/drivers.ini
    - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
    - composer install --no-interaction

script:
    - ./vendor/bin/tester -p php -s -c ./tests/php.ini ./tests/cases
